export default interface ColaboradorEntity {
  IdColaborador: number
  Situacao: boolean
  PontoRemoto: boolean
  Foto: string
  DataNascimento: Date
  Nome: string
  Login: string
  Sexo: string
  Nacionalidade: string
  IdPaisNatal: number
  IdEstadoNatal: number
  EstadoNatalEstrangeiro: string
  IdCidadeNatal: number
  CidadeNatalEstrangeiro: string
  IdEstadoCivil: number
  TelefoneResidencial: string
  TelefoneCelular: string
  CEPResidencia: string
  RuaResidencia: string
  NumeroResidencia: string
  ComplementoResidencia: string
  BairroResidencia: string
  IdPaisResidencia: number
  IdEstadoResidencia: number
  IdCidadeResidencia: number
  Email: string
  Skype: string
  FiliacaoMae: string
  FiliacaoPai: string
  RG: string
  DataExpedicao: Date
  OrgaoExpedidor: string
  CPF: string
  Habilitacao: boolean
  RegistroCNH: string
  TituloEleitor: string
  Passaporte: string
  CartaoTransporteSIC: string
  CartaoTransporteCT: string
  CTPS: string
  Serie: string
  IdEstadoDocumento: number
  PisPasep: string
  IdPreferenciaPagamento: number
  IdBanco: number
  IdTipoContaBancaria: number
  Agencia: string
  NumeroContaBancaria: string
  TipoSanguineo: string
  TipoAlergia: string
  CuidadosEspeciais: string
  DeficienciaFisica: boolean
  PlanoSaude: string
  NumeroPlanoSaude: string
  ContatoEmergencia: string
  TelefoneEmergencia: string
  RazaoSocial: string
  NomeFantasia: string
  CNPJ: string
  InscricaoEstadual: string
  CEPEmpresa: string
  RuaEmpresa: string
  NumeroEmpresa: string
  ComplementoEmpresa: string
  BairroEmpresa: string
  IdPaisEmpresa: number
  IdEstadoEmpresa: number
  IdCidadeEmpresa: number
  IdIndicadoPor: number
  IdPostoTrabalho: number
  InicioPostoTrabalho: Date
  TelefonePostoTrabalho: string
  RamalPostoTrabalho: string
  ObservacaoPostoTrabalho: string
  ValorRestrito: boolean
  LivreDePonto: boolean
  SemRestricaoValorRestrito: boolean
  IdTipoSanguineo: number
  FotoBytes: string
  IdResponsavelAprovacaoDesligamento: number
  IdResponsavelSolicitacaoDesligamento: number
  IdProjetoAreaExecutora: number
  EmailPessoal: string
  PosicaoBancada: string
  LinkedIn: string
  IdDepartamento: number
  Iss: boolean
  Simples: boolean
  AgenciaSicredi: string
  ContaSicredi: string
  IdFellow: number
  DataAtualizacao: Date
  DataAgendamento: Date
}
