export default interface ProjetoEntity {
  IdProjeto: number
  IdProjetoStatus: number
  Nome: string
  IdProjetoTipo: number
  IdCliente: number
  Responsavel: string
  IdColaborador: number
  IdColaboradorGerente: number
  IdColaboradorGerenteDes: number
  IdColaboradorBizDev: number
  IdColaboradorDiretor: number
  DataInicial: Date
  DataFinalAceite: Date
  DataFinalGarantia: Date
  IdProjetoAreaExecutora: number
  IdProjetoAreaNegocio: number
  IdProjetoTipoServico: number
  IdProjetoMercado: number
  IdProjetoTipoUnidade: number
  TamanhoPrevisto: number
  HorasPrevistas: number
  ProdutividadePrevista: number
  OrcamentoVenda: number
  CalculaRetrabalho: boolean
  PDI: boolean
  ControlaCronograma: boolean
  Problema: string
  Solucao: string
  Tecnologia: string
  Metodologia: boolean
  AlocacaoRecursos: boolean
  Milestones: boolean
  Comunicacao: boolean
  Riscos: boolean
  Pendencias: boolean
  PlanoFinanceiro: boolean
  RAGStatus: boolean
  DataCriacao: Date
  DataInicioGerente: Date
  CspVenda: number
  TFSCollection: string
  TFSProjeto: string
  PeriodicidadeAcompanhamento: number
  PontosPositivos: string
  PontosNegativos: string
  SugestaoMelhoriaProcesso: string
  PeriodicidadeAcompanhamentoCliente: number
  NomeParceiro: string
  Comissao: number
  DataRealEntrega: Date
  MissaoProjeto: string
  FaturamentoVendaProjeto: number
  IdProjetoRiscoTolerancia: number
  DataAtualizacaoProjetoRiscoTolerancia: Date
  ResponsavelAtualizacaoProjetoRiscoTolerancia: number
  idMoedas: number
  Atestado: boolean
  DataInicioBizDev: Date
  IdProjetoPMA: number
}
